-- MySQL Script generated by MySQL Workbench
-- Fri Jan  6 00:49:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agencevoyage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agencevoyage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agencevoyage` DEFAULT CHARACTER SET utf8 ;
USE `agencevoyage` ;

-- -----------------------------------------------------
-- Table `agencevoyage`.`période`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencevoyage`.`période` (
  `id_période` INT NOT NULL AUTO_INCREMENT,
  `date_départ` DATE NOT NULL,
  `date_arrivée` DATE NOT NULL,
  PRIMARY KEY (`id_période`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencevoyage`.`circuit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencevoyage`.`circuit` (
  `id_circuit` INT NOT NULL,
  `id_période` INT NOT NULL,
  `nb_places_totales` INT NOT NULL,
  `nb_places_reservées` INT NOT NULL,
  `tarif` DECIMAL(8,2) NOT NULL,
  `descriptif` VARCHAR(45) NOT NULL,
  `libellé` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_circuit`),
  INDEX `fk_circuit_période1_idx` (`id_période` ASC) VISIBLE,
  CONSTRAINT `fk_circuit_période1`
    FOREIGN KEY (`id_période`)
    REFERENCES `agencevoyage`.`période` (`id_période`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencevoyage`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencevoyage`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prénom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencevoyage`.`réservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencevoyage`.`réservation` (
  `id_res` INT NOT NULL AUTO_INCREMENT,
  `id_circuit` INT NOT NULL,
  `id_client` INT NOT NULL,
  `nb_places_demandées` INT NOT NULL,
  `acompte_versé` TINYINT NOT NULL,
  `solde_versé` TINYINT NOT NULL,
  `tarif_initial` DECIMAL(8,2) NOT NULL,
  `date_initialisation` DATE NOT NULL,
  PRIMARY KEY (`id_res`),
  INDEX `fk_réservation_circuit1_idx` (`id_circuit` ASC) VISIBLE,
  INDEX `fk_réservation_client1_idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_réservation_circuit1`
    FOREIGN KEY (`id_circuit`)
    REFERENCES `agencevoyage`.`circuit` (`id_circuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_réservation_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `agencevoyage`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencevoyage`.`paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencevoyage`.`paiement` (
  `id_paiement` INT NOT NULL AUTO_INCREMENT,
  `id_res` INT NOT NULL,
  `date_paiement` DATE NOT NULL,
  `somme` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id_paiement`),
  INDEX `fk_paiement_réservation1_idx` (`id_res` ASC) VISIBLE,
  CONSTRAINT `fk_paiement_réservation1`
    FOREIGN KEY (`id_res`)
    REFERENCES `agencevoyage`.`réservation` (`id_res`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencevoyage`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencevoyage`.`ville` (
  `nom` VARCHAR(45) NOT NULL,
  `région` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencevoyage`.`hôtel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencevoyage`.`hôtel` (
  `id_hôtel` INT NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_hôtel`),
  INDEX `fk_hôtel_ville1_idx` (`ville` ASC) VISIBLE,
  CONSTRAINT `fk_hôtel_ville1`
    FOREIGN KEY (`ville`)
    REFERENCES `agencevoyage`.`ville` (`nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencevoyage`.`déplacement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencevoyage`.`déplacement` (
  `num_journée` INT NOT NULL,
  `id_circuit` INT NOT NULL,
  `ville_départ` VARCHAR(45) NOT NULL,
  `ville_arrivée` VARCHAR(45) NOT NULL,
  `id_hôtel` INT NOT NULL,
  `heure_départ` TIME NOT NULL,
  `heure_arrivée` TIME NOT NULL,
  PRIMARY KEY (`num_journée`),
  INDEX `fk_déplacement_ville1_idx` (`ville_départ` ASC) VISIBLE,
  INDEX `fk_déplacement_hôtel1_idx` (`id_hôtel` ASC) VISIBLE,
  INDEX `fk_déplacement_ville2_idx` (`ville_arrivée` ASC) VISIBLE,
  INDEX `fk_déplacement_circuit1_idx` (`id_circuit` ASC) VISIBLE,
  CONSTRAINT `fk_déplacement_ville1`
    FOREIGN KEY (`ville_départ`)
    REFERENCES `agencevoyage`.`ville` (`nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_déplacement_hôtel1`
    FOREIGN KEY (`id_hôtel`)
    REFERENCES `agencevoyage`.`hôtel` (`id_hôtel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_déplacement_ville2`
    FOREIGN KEY (`ville_arrivée`)
    REFERENCES `agencevoyage`.`ville` (`nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_déplacement_circuit1`
    FOREIGN KEY (`id_circuit`)
    REFERENCES `agencevoyage`.`circuit` (`id_circuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
